### ISSUE TITLE
What's the initial input?

### ISSUE THREAD

**Issue by adriancova** [chejazi/points#2]
"Given the current interval, we should be able to compute the number of active points for each of the previous (completed) N intervals."

So with a current interval 6 and following the last example we would have something like this as initial input?

**Interval number** -> 6
**N** -> 4
**Players current cash spent and points** ->
Alice: $0.25 / 3.5
Bob: $0 / 0 

Really interesting challenge, will take a swing at it but I think I'm missing something, would really appreciate some clarification.

**Comment by chejazi** [comment]
For players, their inputs will be the amount they want to spend as part of playing. It is **OK** to store constant-sized (e.g. < N) data **per player** outside of the algorithms memory constraint. This data can track their activity, e.g. the interval they started, the amount they spent, etc. The interval they participate in is derived from the current time, so they cannot participate in an interval from the past.

For the algorithm that computes historical point totals for each interval, the input will be the interval you wish to read the point total of. If the desired interval is more than N intervals behind the current interval, you can consider the input invalid. E.g. you only need to support the past N intervals, based on whatever the current interval is.

If the current interval is 6 following the last example, points and activity from at least the last 4 intervals will effect the point total for that interval. You will likely need to store information for at least these historical intervals to perform "lookbacks". You can keep this data as long as it doesn't exceed the complexity requirement.

#1
