### ISSUE TITLE
Clarification on submission requirements.

### ISSUE THREAD

**Issue by Markichu** [chejazi/points#5]
I have an idea for an algorithm that determines previous interval total point amounts.
To clarify, the submission needs to only replicate the getIntervalPoints function showed in the skeleton.
Do I also need to implement the actual playing of the game or just show what data is stored by the play function each interval and show the algorithm?

**Comment by chejazi** [comment]
It's okay as long as I can reason about how the algorithm works. You don't need a fully functioning implementation.

**Comment by Markichu** [comment]
Awesome, I am typing it up in rough javascript syntax with comments, hopefully I make the deadline.

**Comment by chejazi** [comment]
I will be reviewing the solutions over the weekend. Good luck!
